### ISSUE TITLE
off-world item sprites swapped

### ISSUE THREAD

**Issue by beauxq** [TestRunnerSRL/SMBasepatch#1]
The 2 off-world item sprites are swapped. It's showing progression when not progression, and not progression when progression.

These are the symbols in the json:
```
    "offworld_graphics_data_item": "89:B700",
    "offworld_graphics_data_progression_item": "89:B600",
```
I double-checked the python code that puts them in the rom.

We could swap where we put them in the rom, but that would confuse people looking at the code in the future.

**Comment by TestRunnerSRL** [comment]
I need to double check that there isn't an off-by-one issue. does the last non-other world item display correctly and ignore the "progression" flag? I think that would be spring ball. If it's just a matter of them being swapped instead, that's easy to fix.

**Comment by beauxq** [comment]
I didn't test a multiworld with SM or SMZ3 yet, to see if those items display correctly.
