### ISSUE TITLE
palettes for off-world items

### ISSUE THREAD

**Issue by beauxq** [TestRunnerSRL/SMBasepatch#2]
The palettes for the off-world items don't look right.

These are the symbols in the json for the palettes:
```
"nonprog_item_eight_palette_indices": "84:F5EA",
"prog_item_eight_palette_indices": "84:F5E0",
```

The data comes from `Archipelago/worlds/sm/data/custom_sprite/`
`off_world_item.bin` and `off_world_prog_item.bin`
The first 8 bytes of each file are the palette that we put at those symbols.

**Comment by TestRunnerSRL** [comment]
Hmm, might be confusion about this. The 8 bytes at the address are the palette line index to use for each of the 8 loaded tiles of the PLM graphics. Typically only palette 0 is used for most PLMs, and occasionally will use palette 1-3. But in either case it does not load a custom palette. The colors are limited to what was already loaded by the room tileset graphics.

**Comment by beauxq** [comment]
I copied the pattern for how SM puts that palette information in those symbol addresses.
I wonder if SM did something else to make sure the right colors are loaded, or if the right colors just happen to always be loaded in SM... I dunno.

**Comment by TestRunnerSRL** [comment]
I provided updated graphics for this. It only uses palette line 0, so you should see that the first 8 bytes are all 00.
