### ISSUE TITLE
message box stays open too long when receiving major items

### ISSUE THREAD

**Issue by beauxq** [TestRunnerSRL/SMBasepatch#3]
When I receive a major item from another player, it doesn't let me close the message box for 6 seconds, and the music resets.

In AP, sometimes we receive many items (40-50+) at once, and it would be annoying if we couldn't dismiss all the message boxes faster.

The behavior for the minor items is good. It would be good if the major items behaved the same as the minor items.

**Comment by beauxq** [comment]
One approach to consider:
If we made a new patch, separate from the multiworld patch that made this change for the 1-player SubversionRando, then we could make that an option for the 1-player rando ("short fanfares").
If we did that, would that fix the problem for the message boxes in multiworld?

We could apply that patch optionally in SubversionRando, and apply it on every AP game.

**Comment by TestRunnerSRL** [comment]
The normal items are handled a bit differently, So I think if you wanted to have a patch for that it should be handled separately

**Comment by beauxq** [comment]
The reason I thought it might work that way is because of the amount of time, and the music reset.
If it's not from the normal item handling, where is it getting the 6 seconds from? and where is it getting the music reset from?

**Comment by beauxq** [comment]
The music still resets after 6 seconds.
(for a local major item with short fanfare)

**Comment by TestRunnerSRL** [comment]
To clarify, is this a problem for any received item, received major item, received specific items, collected major/minor, sent major/minor? There's a lot of ways to have message boxes appear, so I want to make sure I'm looking for the right thing here.

**Comment by beauxq** [comment]
collected major items (1 player game generated with AP with AP multiworld patch)
